# -*- coding: utf-8 -*-
"""v5_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHyIHGZVF1ZIPScoXZtqdYiq0ISLySVp
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5

!pip install -r requirements.txt
!pip install comet_ml

from google.colab import drive
drive.mount('/content/drive')

import os

# my dataset location on Drive
source_base = '/content/drive/MyDrive/AML/military aircraft-20250316T201220Z-001/militaryAircraft'
source_train = os.path.join(source_base, 'train')
source_test = os.path.join(source_base, 'test')
source_yaml = os.path.join(source_base, 'data.yaml')

# YOLOv5 expects it here
target_base = '/content/yolov5/datasets'
target_train = os.path.join(target_base, 'train')
target_test = os.path.join(target_base, 'test')
target_yaml = os.path.join(target_base, 'data.yaml')

os.makedirs(target_base, exist_ok=True)

for src, tgt in [(source_train, target_train), (source_test, target_test), (source_yaml, target_yaml)]:
    if not os.path.exists(tgt):
        os.symlink(src, tgt)
        print(f"Linked: {src} -> {tgt}")
    else:
        print(f"Already exists: {tgt}")

import comet_ml
comet_ml.login(api_key="SmUGipAJkSNWIzSHbN2ODZHqz")

!python train.py \
  --data datasets/data.yaml \
  --weights yolov5s.pt \
  --project v5-baseline \
  --name yolov5-default \
  --exist-ok