# -*- coding: utf-8 -*-
"""v8_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhwWYpWUF25QShiZUDzdgEn-eLP-EbVR
"""

!pip install ultralytics

!pip install comet_ml

from google.colab import drive
drive.mount('/content/drive')

import os

# Your dataset location on Drive
source_base = '/content/drive/MyDrive/AML/military aircraft-20250316T201220Z-001/militaryAircraft'
source_train = os.path.join(source_base, 'train')
source_test = os.path.join(source_base, 'test')
source_yaml = os.path.join(source_base, 'data.yaml')

# Organize under YOLOv8 folder
target_base = '/content/yolov8/datasets'
os.makedirs(target_base, exist_ok=True)

# Symlink data
for src, name in [(source_train, 'train'), (source_test, 'test'), (source_yaml, 'data.yaml')]:
    target = os.path.join(target_base, name)
    if not os.path.exists(target):
        os.symlink(src, target)
        print(f"Linked: {src} -> {target}")
    else:
        print(f"Already exists: {target}")

import comet_ml
comet_ml.init(api_key="SmUGipAJkSNWIzSHbN2ODZHqz", workspace="razan4949", project_name="yolo8-baseline")

# Run YOLOv8 training
from ultralytics import YOLO

model = YOLO('yolov8m.pt')

results = model.train(
    data=os.path.join(target_base, 'data.yaml'),
    epochs=100,
    imgsz=640,
    batch=16,
    name='yolov8-baseline',
    project='/content/yolov8/runs',
    device=0,
    save=True
)